packages:
  - "apps/*"
  - "packages/*"
  - "playground/*"

catalog:
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@tanstack/react-query': ^5.90.7
  '@types/lodash': ^4.17.20
  '@types/node': 24.10.0
  bun-types: ^1.3.2
  client-only: ^0.0.1
  dayjs: ^1.11.19
  graphql-request: ^7.3.1
  ky: ^1.14.0
  lodash: ^4.17.21
  server-only: ^0.0.1
  superjson: 2.2.5
  typescript: ^5.9.3
  zod: ^4.1.12
  tsdown: ^0.16.1

catalogs:
  eslint:
    '@eslint/js': 9.39.1
    eslint: 9.39.1
  next-is:
    '@next/bundle-analyzer': 16.0.3
    '@next/eslint-plugin-next': 16.0.3
    '@next/third-parties': 16.0.3
    next: 16.0.3
  react-is:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: ^19.2.0
    react-dom: ^19.2.0
  tailwindcss:
    '@tailwindcss/postcss': 4.1.17
    tailwindcss: 4.1.17

linkWorkspacePackages: true