packages:
  - apps/docs
  - apps/ts-docs
  - packages/*
  - playground/*

catalog:
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@types/lodash': ^4.17.20
  '@types/node': 25.0.1
  bun-types: ^1.3.2
  client-only: ^0.0.1
  dayjs: ^1.11.19
  graphql-request: ^7.3.1
  ky: ^1.14.1
  lodash: ^4.17.21
  server-only: ^0.0.1
  superjson: 2.2.5
  tsdown: ^0.17.3
  typescript: ^5.9.3
  zod: 4.1.13

catalogs:
  eslint:
    '@eslint/js': 9.39.1
    eslint: 9.39.1
  fumadocs:
    'fumadocs-core': 16.2.5
    'fumadocs-mdx': 14.1.0
    'fumadocs-ui': 16.2.5
  next-is:
    '@next/bundle-analyzer': 16.0.10
    '@next/eslint-plugin-next': 16.0.10
    '@next/third-parties': 16.0.10
    next: 16.1.5
  react-canary:
    react: 19.3.0-canary-fb2177c1-20251114
    react-dom: 19.3.0-canary-fb2177c1-20251114
  react-is:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    babel-plugin-react-compiler: 1.0.0
    react: ^19.2.3
    react-dom: ^19.2.3
  tailwindcss:
    '@tailwindcss/postcss': 4.1.18
    '@tailwindcss/vite': 4.1.18
    tailwindcss: 4.1.18
  tanstack:
    '@tanstack/pacer': 0.16.3
    '@tanstack/react-query': ^5.90.7
    '@tanstack/react-router': ^1.141.1
    '@tanstack/react-router-devtools': ^1.141.1
    '@tanstack/react-start': ^1.141.1
    '@tanstack/router-plugin': ^1.141.1
  vite:
    '@vitejs/plugin-react': 5.1.2
    vite: 7.2.7
    'vite-tsconfig-paths': 5.1.4

linkWorkspacePackages: true
